import Head from 'next/head'
import Image from 'next/image'

import Banner from '../components/banner/banner'
import Card from '../components/card/card'

import styles from '../styles/home.module.css'

import coffeeStores from '../data/coffee-stores.json';

export default function Home() {

  const handleOnBannerClick = () => {
    console.log('IN')
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Coffee Connoisseur</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Banner
          buttonText="View stores nearby"
          handleClick={handleOnBannerClick} />

        <div className={styles.heroImage}>
          <Image
            src='/static/hero-image.png'
            width={700}
            height={400}
            alt='hero'
          />
        </div>
        <div className={styles.cardLayout}>
          {coffeeStores.map(coffeeStore => {
            return (
              <Card
                key={coffeeStore.id}
                className={styles.card}
                name={coffeeStore.name}
                href={`/coffee-store/${coffeeStore.id}`}
                imgUrl={coffeeStore.imgUrl}
              />
            )
          })}
        </div>
      </main>
    </div>
  )
}
