import Head from 'next/head'
import Image from 'next/image'

import Banner from '../components/banner/banner'
import Card from '../components/card/card'

import styles from '../styles/home.module.css'

import coffeeStoresData from '../data/coffee-stores.json';


export async function getStaticProps(context) {
  return {
    props: {
      coffeeStores: coffeeStoresData
    }
  }
}

export default function Home({ coffeeStores }) {

  const handleOnBannerClick = () => {
    console.log('IN')
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Coffee Connoisseur</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Banner
          buttonText="View stores nearby"
          handleClick={handleOnBannerClick} />

        <div className={styles.heroImage}>
          <Image
            src='/static/hero-image.png'
            width={700}
            height={400}
            alt='hero'
          />
        </div>
        {coffeeStores.length && (
          <>
            <h2 className={styles.heading2}>Toronto Stores</h2>
            <div className={styles.cardLayout}>
              {coffeeStores.map(coffeeStore => {
                return (
                  <Card
                    key={coffeeStore.id}
                    className={styles.card}
                    name={coffeeStore.name}
                    href={`/coffee-store/${coffeeStore.id}`}
                    imgUrl={coffeeStore.imgUrl}
                  />
                )
              })}
            </div>
          </>
        )}

      </main>
    </div>
  )
}

